spring:
  datasource:
    url: jdbc:oracle:thin:@productobd_high?TNS_ADMIN=/app/oracle_wallet
    username: "ADMIN"
    password: " Producto2026!Secure"

server:
  port: ${PORT:8086}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka/}
  instance:
    prefer-ip-address: true